/* Generated By:JavaCC: Do not edit this line. PestParserConstants.java */
package budapest.pest.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PestParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int LOCAL = 10;
  /** RegularExpression Id. */
  int SKIP_T = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int THEN = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int FIND = 17;
  /** RegularExpression Id. */
  int FIRST = 18;
  /** RegularExpression Id. */
  int LAST = 19;
  /** RegularExpression Id. */
  int MAP = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int FORALL = 23;
  /** RegularExpression Id. */
  int EXISTS = 24;
  /** RegularExpression Id. */
  int FROM = 25;
  /** RegularExpression Id. */
  int TO = 26;
  /** RegularExpression Id. */
  int IDENTIFIER = 27;
  /** RegularExpression Id. */
  int LETTER = 28;
  /** RegularExpression Id. */
  int DIGIT = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"local\"",
    "\"skip\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"find\"",
    "\"first\"",
    "\"last\"",
    "\"map\"",
    "\"in\"",
    "\"for\"",
    "\"forall\"",
    "\"exists\"",
    "\"from\"",
    "\"to\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\":*\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":?\"",
    "\":!\"",
    "\":?!\"",
    "\":#\"",
    "\":@@@\"",
    "\":!!!\"",
    "\"<-\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"=\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\":\"",
    "\"@pre\"",
  };

}
